# Ficheiro: .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ou a sua branch principal
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Usa uma versão LTS do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Executa o nosso script de build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload da nossa pasta 'deploy'
          path: './deploy'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4